2025-01-09 21:41:40.485 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:41:40.720 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:41:40.728 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:41:41.408 | INFO     | model.model_service:load_models:174 - 2 models found and loaded.
2025-01-09 21:41:41.409 | INFO     | model.model_service:get_preds:231 - Predicting for SMILE: CC(=O)N1CCCC1
2025-01-09 21:41:41.587 | INFO     | model.model_service:get_preds:243 - solvation free energy:-4.53 Â± 0.201
2025-01-09 21:41:41.587 | INFO     | model.model_service:get_preds:231 - Predicting for SMILE: CCCCCCCC(=O)OC
2025-01-09 21:41:41.595 | INFO     | model.model_service:get_preds:243 - solvation free energy:-2.62 Â± 0.113
2025-01-09 21:42:06.917 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:42:07.146 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:42:07.147 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:42:07.156 | ERROR    | __main__:<module>:17 - An error has been caught in function '<module>', process 'MainProcess' (4089), thread 'MainThread' (139744941682752):
Traceback (most recent call last):

> File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 17, in <module>
    main()
    â”” <function main at 0x7f18e7484680>

  File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 9, in main
    gcn_multi.load_models()
    â”‚         â”” <function ModelService.load_models at 0x7f17c9f61760>
    â”” <model.model_service.ModelService object at 0x7f18e7495e90>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in load_models
    self.models = [torch.load(model_name, weights_only=True)
    â”‚    â”‚         â”‚     â”” <function load at 0x7f184b7f4040>
    â”‚    â”‚         â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>
    â”‚    â”” []
    â”” <model.model_service.ModelService object at 0x7f18e7495e90>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in <listcomp>
    self.models = [torch.load(model_name, weights_only=True)
                   â”‚     â”‚    â”” PosixPath('model/models/optimized_gcn_seed_136.pt')
                   â”‚     â”” <function load at 0x7f184b7f4040>
                   â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>

  File "/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1359, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
          â”‚      â”‚               â”” <function load.<locals>._get_wo_message at 0x7f17c9f63c40>
          â”‚      â”” <class '_pickle.UnpicklingError'>
          â”” <module 'pickle' from '/usr/lib/python3.11/pickle.py'>

_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL model.ChemGCN was not an allowed global by default. Please use `torch.serialization.add_safe_globals([ChemGCN])` to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
2025-01-09 21:43:58.833 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:43:59.077 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:43:59.084 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:43:59.086 | ERROR    | __main__:<module>:17 - An error has been caught in function '<module>', process 'MainProcess' (4484), thread 'MainThread' (140096497938496):
Traceback (most recent call last):

> File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 17, in <module>
    main()
    â”” <function main at 0x7f6ac1ab0680>

  File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 9, in main
    gcn_multi.load_models()
    â”‚         â”” <function ModelService.load_models at 0x7f69a4579760>
    â”” <model.model_service.ModelService object at 0x7f6ac1ac1d50>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in load_models
    self.models = [torch.load(model_name, weights_only=True)
    â”‚    â”‚         â”‚     â”” <function load at 0x7f6a25d18040>
    â”‚    â”‚         â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>
    â”‚    â”” []
    â”” <model.model_service.ModelService object at 0x7f6ac1ac1d50>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in <listcomp>
    self.models = [torch.load(model_name, weights_only=True)
                   â”‚     â”‚    â”” PosixPath('model/models/optimized_gcn_seed_136.pt')
                   â”‚     â”” <function load at 0x7f6a25d18040>
                   â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>

  File "/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1359, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
          â”‚      â”‚               â”” <function load.<locals>._get_wo_message at 0x7f69a457bc40>
          â”‚      â”” <class '_pickle.UnpicklingError'>
          â”” <module 'pickle' from '/usr/lib/python3.11/pickle.py'>

_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL model.ChemGCN was not an allowed global by default. Please use `torch.serialization.add_safe_globals([ChemGCN])` to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
2025-01-09 21:44:24.344 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:44:24.580 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:44:24.581 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:44:25.079 | ERROR    | __main__:<module>:17 - An error has been caught in function '<module>', process 'MainProcess' (4653), thread 'MainThread' (140165869830208):
Traceback (most recent call last):

> File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 17, in <module>
    main()
    â”” <function main at 0x7f7ae88e0680>

  File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 9, in main
    gcn_multi.load_models()
    â”‚         â”” <function ModelService.load_models at 0x7f79cb32d760>
    â”” <model.model_service.ModelService object at 0x7f79cc33ab50>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in load_models
    self.models = [torch.load(model_name, weights_only=True)
    â”‚    â”‚         â”‚     â”” <function load at 0x7f7a6f7f4040>
    â”‚    â”‚         â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>
    â”‚    â”” []
    â”” <model.model_service.ModelService object at 0x7f79cc33ab50>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in <listcomp>
    self.models = [torch.load(model_name, weights_only=True)
                   â”‚     â”‚    â”” PosixPath('model/models/optimized_gcn_seed_75.pt')
                   â”‚     â”” <function load at 0x7f7a6f7f4040>
                   â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>

  File "/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1359, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
          â”‚      â”‚               â”” <function load.<locals>._get_wo_message at 0x7f79cb32fc40>
          â”‚      â”” <class '_pickle.UnpicklingError'>
          â”” <module 'pickle' from '/usr/lib/python3.11/pickle.py'>

_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL model.ChemGCN was not an allowed global by default. Please use `torch.serialization.add_safe_globals([ChemGCN])` to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
2025-01-09 21:44:33.478 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:44:33.711 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:44:33.711 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:44:34.199 | INFO     | model.model_service:load_models:174 - 2 models found and loaded.
2025-01-09 21:44:34.199 | INFO     | model.model_service:get_preds:231 - Predicting for SMILE: CC(=O)N1CCCC1
2025-01-09 21:44:34.368 | INFO     | model.model_service:get_preds:243 - solvation free energy:-4.53 Â± 0.201
2025-01-09 21:44:34.369 | INFO     | model.model_service:get_preds:231 - Predicting for SMILE: CCCCCCCC(=O)OC
2025-01-09 21:44:34.372 | INFO     | model.model_service:get_preds:243 - solvation free energy:-2.62 Â± 0.113
2025-01-09 21:44:53.437 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:44:53.668 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:44:53.669 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:44:54.129 | ERROR    | __main__:<module>:17 - An error has been caught in function '<module>', process 'MainProcess' (4898), thread 'MainThread' (140376729595968):
Traceback (most recent call last):

> File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 17, in <module>
    main()
    â”” <function main at 0x7fac00c6c680>

  File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 9, in main
    gcn_multi.load_models()
    â”‚         â”” <function ModelService.load_models at 0x7faae3631760>
    â”” <model.model_service.ModelService object at 0x7fac00c7de90>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in load_models
    self.models = [torch.load(model_name, weights_only=True)
    â”‚    â”‚         â”‚     â”” <function load at 0x7fab64ff4040>
    â”‚    â”‚         â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>
    â”‚    â”” []
    â”” <model.model_service.ModelService object at 0x7fac00c7de90>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in <listcomp>
    self.models = [torch.load(model_name, weights_only=True)
                   â”‚     â”‚    â”” PosixPath('model/models/optimized_gcn_seed_241.pt')
                   â”‚     â”” <function load at 0x7fab64ff4040>
                   â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>

  File "/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1359, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
          â”‚      â”‚               â”” <function load.<locals>._get_wo_message at 0x7faae3633c40>
          â”‚      â”” <class '_pickle.UnpicklingError'>
          â”” <module 'pickle' from '/usr/lib/python3.11/pickle.py'>

_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL model.ChemGCN was not an allowed global by default. Please use `torch.serialization.add_safe_globals([ChemGCN])` to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
2025-01-09 21:45:18.310 | INFO     | model.pipeline.collection:load_from_db:237 - Loading data from database
2025-01-09 21:45:18.546 | INFO     | model.pipeline.model:initialize_standardizer:459 - Created standardizer from outputs
2025-01-09 21:45:18.547 | DEBUG    | model.model_service:_set_globals:88 - Following globals set as safe: [<class 'set'>, <class 'model.pipeline.model.ChemGCN'>, <class 'model.pipeline.model.ConvolutionLayer'>, <class 'model.pipeline.model.PoolingLayer'>, <class 'torch.nn.modules.linear.Linear'>, <class 'torch.nn.modules.container.ModuleList'>, <class 'torch.nn.modules.activation.LeakyReLU'>, <class 'torch.nn.modules.dropout.Dropout'>]
2025-01-09 21:45:18.548 | ERROR    | __main__:<module>:17 - An error has been caught in function '<module>', process 'MainProcess' (5052), thread 'MainThread' (140277348245568):
Traceback (most recent call last):

> File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 17, in <module>
    main()
    â”” <function main at 0x7f94dd2f8680>

  File "/home/papafrita/projects/soluGNN/solugnn/runner.py", line 9, in main
    gcn_multi.load_models()
    â”‚         â”” <function ModelService.load_models at 0x7f93bfd75760>
    â”” <model.model_service.ModelService object at 0x7f94dd309d50>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in load_models
    self.models = [torch.load(model_name, weights_only=True)
    â”‚    â”‚         â”‚     â”” <function load at 0x7f943471c040>
    â”‚    â”‚         â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>
    â”‚    â”” []
    â”” <model.model_service.ModelService object at 0x7f94dd309d50>

  File "/home/papafrita/projects/soluGNN/solugnn/model/model_service.py", line 169, in <listcomp>
    self.models = [torch.load(model_name, weights_only=True)
                   â”‚     â”‚    â”” PosixPath('model/models2/optimized_gcn_seed_136.pt')
                   â”‚     â”” <function load at 0x7f943471c040>
                   â”” <module 'torch' from '/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/__init__.py'>

  File "/home/papafrita/projects/soluGNN/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1359, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
          â”‚      â”‚               â”” <function load.<locals>._get_wo_message at 0x7f93bfd77c40>
          â”‚      â”” <class '_pickle.UnpicklingError'>
          â”” <module 'pickle' from '/usr/lib/python3.11/pickle.py'>

_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL model.ChemGCN was not an allowed global by default. Please use `torch.serialization.add_safe_globals([ChemGCN])` to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
